### ISSUE TITLE
AppArmor errors with automatic key management

### ISSUE THREAD

**Issue by smoeding** [smoeding/puppet-bind#7]
Automatic key management is not possible if AppArmor is enabled. The AppArmor rules in Debian prevent `named` to create any files below `/etc`. The following error occurs:
```
apparmor="DENIED" operation="mknod" profile="named" name="/etc/bind/keys/Kkill-9.net.+013+19420.key" pid=519 
comm="isc-net-0001" requested_mask="c" denied_mask="c" fsuid=142 ouid=142
```

 The keys will have to be managed either below `/var/cache` or `/var/lib`.

**Comment by sboyd-m** [comment]
FWIW I was able to get around this by adding a local override to apparmor for this. They include that as a feature for a reason.

```
cat /etc/apparmor.d/local/usr.sbin.named

# vim:syntax=apparmor
# This file is managed by puppet

# Enable Bind to manage its own DNSSEC keys
/etc/bind/keys/** rw,
```

Then in puppet:
```  file_line { 'Include bind apparmor overrides':
    path   => '/etc/apparmor.d/usr.sbin.named',
    line   => 'include <local/usr.sbin.named>',
    match  => '#include <local/usr.sbin.named>',
    notify => Service['apparmor'],
  }

  file { '/etc/apparmor.d/local/usr.sbin.named':
    content => file('profile/usr.sbin.named'),
    notify  => Service['apparmor'],
  }

  service { 'apparmor':
    subscribe => [
      File_line['Include bind apparmor overrides'],
      File['/etc/apparmor.d/local/usr.sbin.named'],
    ],
  }
  ```
  
 Not sure if this is the route you would want to go with a module, but it works great for me.

Note: One reason I think it is better than changing the bind config is if you change the key location, someone has to move those keys by hand, and there is statefulness in them, etc. The changes I have here would allow anyone to upgrade the module and have things "just work".

**Comment by smoeding** [comment]
Thanks for your feedback! I haven't decided how to handle this. As you said it would require a move of key files when updating. On the other hand did I keep the semantic version number below 1.0.0 because I wasn't sure that things like this would happen.
Deploying a AppArmor file with the module looks good. But the AppArmor service shoudn't be managed from this module so there is a drawback.

**Comment by sboyd-m** [comment]
>But the AppArmor service shoudn't be managed from this module so there is a drawback

I agree. I wish there were an apparmor module, but there doesn't seem to be one. I guess Someone™ needs to write one!
I think for now, a minimum solution would be to include what I have above in the documentation somewhere, so at least people can have a starting point if they are stuck.

**Comment by smoeding** [comment]
I'm not really happy with including too much AppArmor specific code into the module. I think it will create too much work in the long run. The module is still at major version zero, so incompatible changes are acceptable. I'll change the code to put the managed keys somewhere below `/var/lib/bind`.
